### ISSUE TITLE
trained models

### ISSUE THREAD

**Issue by abhinine4** [yahoo/spivak#5]
Hi Authors,

Will you be releasing the trained models for Action spotting ? 
Or if its already available, can you point me to it?

thank you !

**Comment by jvbsoares** [comment]
Hi Abhishek,
Thanks for your interest. We might eventually release our models if there is enough interest. However, that would still take us some weeks or months to prepare and get internal approvals, as we try to prioritize different improvements. Being so, at the moment we recommend that you try to follow our documentation for training models and please let us know if you run into issues or have any questions.

**Comment by abhinine4** [comment]
Sure @jvbsoares . Thank you for letting us know.

**Comment by Y-Haneji** [comment]
@jvbsoares 
I'm also interested in your models. Therefore, if you have time, could you consider to release them later?

**Comment by jvbsoares** [comment]
Thank you for letting us know of your interest! We'll work on releasing the models. Please be patient with us, since we'll need some weeks in order to prepare the models and get approvals.

**Comment by jvbsoares** [comment]
We have just released a set of pretrained models. Please see https://github.com/yahoo/spivak/pull/13

**Comment by jvbsoares** [comment]
The related instructions are at https://github.com/yahoo/spivak/blob/master/Reproducing-results-from-the-SoccerNet-action-spotting-challenge-2022.md
